// <auto-generated />
using System;
using System.Collections.Generic;
using Inmobiliaria.Infrastructure.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inmobiliaria.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240209060811_create-financial-data")]
    partial class createfinancialdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inmobiliaria.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Identity", "Inmobiliaria.Domain.Customers.Customer.Identity#Identity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DateOfIssue")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Tuition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Coordinates", "Inmobiliaria.Domain.Properties.Property.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("East")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("North")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("South")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("West")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.SaleCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Identity", "Inmobiliaria.Domain.Sales.SaleCustomer.Identity#Identity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DateOfIssue")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("SaleCustomer", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.SaleFinancialData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CompensationFundSubsidy")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<string>("LoanEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LoanValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinistryOfHousingSubsidy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherPayments")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValueToSetAside")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("SaleFinancialData", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.SaleProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tuition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Coordinates", "Inmobiliaria.Domain.Sales.SaleProperty.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("East")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("North")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("South")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("West")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("SaleProperty", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.SaleCustomer", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Customers.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inmobiliaria.Domain.Sales.Sale", "Sale")
                        .WithOne("Customer")
                        .HasForeignKey("Inmobiliaria.Domain.Sales.SaleCustomer", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.SaleFinancialData", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Sales.Sale", "Sale")
                        .WithOne("FinancialData")
                        .HasForeignKey("Inmobiliaria.Domain.Sales.SaleFinancialData", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.SaleProperty", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Properties.Property", "Property")
                        .WithMany("Sales")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inmobiliaria.Domain.Sales.Sale", "Sale")
                        .WithOne("Property")
                        .HasForeignKey("Inmobiliaria.Domain.Sales.SaleProperty", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Properties.Property", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("FinancialData")
                        .IsRequired();

                    b.Navigation("Property")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
